In [ ]:
import random
import string
def shorten_url():
    letters = string.ascii_lowercase + string.ascii_uppercase+string.digits
    while True:
        random_letters = random.choices(letters, k=6)
        random_letters = "".join(random_letters)
        return random_letters
#         short_url = url.query.filter_by(short=random_letters).first()
        if not short_url:
            return random_letters

In [ ]:
shorten_url()

In [ ]:
import random, string
def shorten_url():
    letters = string.ascii_lowercase + string.ascii_uppercase + string.digits
    while True:
        rand_letters = random.choices(letters, k=10)
        rand_letters = "".join(rand_letters)
        return rand_letters
#         short_url = Url.query.filter_by(short=rand_letters).first()
#         if not short_url:

In [ ]:
shorten_url()

In [ ]:
print(random.randint(1000,9999))

In [ ]:
import hashlib as hlb
original_url="https://github.com/ShubhamSalokhe/REGex-Tasks/tree/main/Task%2010"
shorten_url =hlb.md5(original_url.encode("utf-8")).hexdigest()[:9][::-1]
print(shorten_url)

In [1]:
import PyPDF2 as pdf
import pandas as pd

In [2]:
df = open('CummulativeCovidVaccinationReport07January2022.pdf',"rb")

In [3]:
pdfReader = pdf.PdfFileReader(df)
pageObj = pdfReader.getPage(0)
extract= pageObj.extractText()
splitex= extract.split('\n')

In [4]:
splitex

["(As on 08 Jan'22 at 7 AM)",
 '15-18 Years',
 '1st Dose',
 '2nd Dose',
 'Total Doses',
 '1st Dose',
 '85,83,23,079',
 '62,76,35,244',
 '1,48,59,58,323',
 '2,02,34,580',
 '(22,72,120 in last 24 ',
 'Hours )',
 '(35,31,325 in last 24 ',
 'Hours)',
 '(58,03,445 in last 24 ',
 'Hours)',
 '(32,55,915 in last 24 ',
 'Hours )',
 '0',
 '0',
 '0',
 '0',
 '15-18 Years',
 '1st Dose',
 '2nd Dose',
 'Total Doses',
 '1st Dose',
 '1',
 'A & N Islands',
 '3,03,740',
 '2,95,713',
 '5,99,453',
 '9,968',
 '2',
 'Andhra Pradesh',
 '4,00,82,487',
 '3,07,28,752',
 '7,08,11,239',
 '17,99,919',
 '3',
 'Arunachal Pradesh',
 '8,11,910',
 '6,55,590',
 '14,67,500',
 '12,199',
 '4',
 'Assam',
 '2,19,27,601',
 '1,62,50,752',
 '3,81,78,353',
 '5,45,176',
 '5',
 'Bihar',
 '5,84,94,171',
 '4,33,15,480',
 '10,18,09,651',
 '13,33,297',
 '6',
 'Chandigarh',
 '10,28,191',
 '7,97,205',
 '1825396',
 '12278',
 '7',
 'Chhattisgarh',
 '1,79,77,433',
 '1,25,78,825',
 '3,05,56,258',
 '6,93,543',
 '8',
 'Dadra & Nagar ',
 'Haveli',
 '4,14,480',
 '2,94,941',
 '709421',
 '14213',
 '9',
 'Daman & Diu',
 '2,93,562',
 '2,43,997',
 '537559',
 '8884',
 '10',
 'Delhi',
 '1,56,03,453',
 '1,15,73,778',
 '2,71,77,231',
 '2,04,882',
 '11',
 'Goa',
 '13,19,508',
 '11,20,515',
 '2440023',
 '33305',
 '12',
 'Gujarat',
 '4,75,82,358',
 '4,33,84,764',
 '9,09,67,122',
 '17,71,871',
 '13',
 'Haryana',
 '2,07,73,925',
 '1,52,03,393',
 '3,59,77,318',
 '5,28,002',
 '14',
 'Himachal Pradesh',
 '59,29,163',
 '55,11,230',
 '1,14,40,393',
 '2,40,811',
 '15',
 'Jammu & Kashmir',
 '97,43,018',
 '92,82,520',
 '1,90,25,538',
 '1,85,636',
 '16',
 'Jharkhand',
 '1,90,00,422',
 '1,16,98,643',
 '3,06,99,065',
 '2,62,095',
 '17',
 'Karnataka',
 '4,83,05,734',
 '3,95,27,725',
 '8,78,33,459',
 '15,26,215',
 '18',
 'Kerala',
 '2,63,70,455',
 '2,15,58,246',
 '4,79,28,701',
 '3,18,610',
 '19',
 'Ladakh',
 '2,15,780',
 '1,76,050',
 '391830',
 '5018',
 '20',
 'Lakshadweep',
 '56,175',
 '53,092',
 '109267',
 '1823',
 '21',
 'Madhya Pradesh',
 '5,27,43,860',
 '5,05,20,223',
 '10,32,64,083',
 '19,70,970',
 '22',
 'Maharashtra',
 '8,11,97,428',
 '5,56,26,731',
 '13,68,24,159',
 '14,83,877',
 '23',
 'Manipur',
 '13,33,806',
 '10,05,182',
 '2338988',
 '4381',
 '24',
 'Meghalaya',
 '12,43,080',
 '8,95,169',
 '2138249',
 '5912',
 '25',
 'Mizoram',
 '7,50,199',
 '5,91,411',
 '1341610',
 '10392',
 '26',
 'Nagaland',
 '7,60,450',
 '5,79,961',
 '13,40,411',
 '1,200',
 '27',
 'Odisha',
 '2,96,97,758',
 '2,18,70,982',
 '5,15,68,740',
 '4,12,003',
 '28',
 'Puducherry',
 '8,55,834',
 '5,76,678',
 '1432512',
 '18928',
 '29',
 'Punjab',
 '1,74,12,664',
 '97,91,030',
 '2,72,03,694',
 '24,683',
 '30',
 'Rajasthan',
 '4,74,88,007',
 '3,60,61,353',
 '8,35,49,360',
 '16,18,130',
 '31',
 'Sikkim',
 '5,29,700',
 '4,84,483',
 '1014183',
 '10557',
 '32',
 'Tamil Nadu',
 '5,06,72,703',
 '3,48,27,655',
 '8,55,00,358',
 '14,63,852',
 '33',
 'Telangana',
 '2,82,68,742',
 '1,98,90,649',
 '4,81,59,391',
 '6,08,895',
 '34',
 'Tripura',
 '25,99,926',
 '21,39,818',
 '47,39,744',
 '70,887',
 '35',
 'Uttar Pradesh',
 '13,11,71,604',
 '7,77,02,415',
 '20,88,74,019',
 '17,16,491',
 '36',
 'Uttarakhand',
 '79,08,600',
 '65,51,063',
 '1,44,59,663',
 '2,66,268',
 '37',
 'West Bengal',
 '6,52,17,243',
 '4,26,98,608',
 '10,79,15,851',
 '10,39,409',
 '38',
 'Miscellaneous',
 '22,37,909',
 '15,70,622',
 '38,08,531',
 '0',
 'Beneficiaries Vaccinated',
 '18+ Population',
 'Cumulative Coverage Report of COVID-19 Vaccination',
 'S. No.',
 'State/UT',
 'Beneficiaries Vaccinated',
 '18+ Population',
 '']

In [22]:
states = ['A & N Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli',
 'Daman & Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [23]:
pd.DataFrame({"State":states}).to_csv("states.csv",index_label=False)

In [24]:
states  = pd.read_csv("states.csv")
len(states)

37

In [32]:
states= states["State"].values

array(['A & N Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam',
       'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli',
       'Daman & Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana',
       'Himachal Pradesh', 'Jammu & Kashmir', 'Jharkhand', 'Karnataka',
       'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal'], dtype=object)

In [6]:
len(states)

37

In [9]:
state_doses = pd.DataFrame({"state":[],
               "state_num":[],
               "1st Dose":[],
               "2nd Dose":[],
               "Total Doses":[],
               "1st Dose(15-18)":[]
                })

In [ ]:
states[0:7]

In [10]:
for i in states:
    if i != 'Dadra & Nagar Haveli':
        index = splitex.index(i)
        state_no = int(splitex[index-1])
        state_name = splitex[index]
        stname_no = [state_name,state_no]
        doses= splitex[index+1:index+5]
        total = stname_no +[int(i.replace(",","")) for i in doses]
        state_doses= state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)  
        
    elif i == 'Dadra & Nagar Haveli':
        index = splitex.index("Dadra & Nagar ")
        state_no = int(splitex[index-1])
        state_name = i
        stname_no = [state_name,state_no]
        state_name = splitex[index]
        doses= splitex[index+2:index+6]
        total = stname_no +[int(i.replace(",","")) for i in doses]
        state_doses=state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)

In [13]:
state_doses

,state,state_num,1st Dose,2nd Dose,Total Doses,1st Dose(15-18)
0,A & N Islands,1.0,303740.0,295713.0,599453.0,9968.0
1,Andhra Pradesh,2.0,40082487.0,30728752.0,70811239.0,1799919.0
2,Arunachal Pradesh,3.0,811910.0,655590.0,1467500.0,12199.0
3,Assam,4.0,21927601.0,16250752.0,38178353.0,545176.0
4,Bihar,5.0,58494171.0,43315480.0,101809651.0,1333297.0
5,Chandigarh,6.0,1028191.0,797205.0,1825396.0,12278.0
6,Chhattisgarh,7.0,17977433.0,12578825.0,30556258.0,693543.0
7,Dadra & Nagar Haveli,8.0,414480.0,294941.0,709421.0,14213.0
8,Daman & Diu,9.0,293562.0,243997.0,537559.0,8884.0
9,Delhi,10.0,15603453.0,11573778.0,27177231.0,204882.0
10,Goa,11.0,1319508.0,1120515.0,2440023.0,33305.0
11,Gujarat,12.0,47582358.0,43384764.0,90967122.0,1771871.0
12,Haryana,13.0,20773925.0,15203393.0,35977318.0,528002.0
13,Himachal Pradesh,14.0,5929163.0,5511230.0,11440393.0,240811.0
14,Jammu & Kashmir,15.0,9743018.0,9282520.0,19025538.0,185636.0
15,Jharkhand,16.0,19000422.0,11698643.0,30699065.0,262095.0
16,Karnataka,17.0,48305734.0,39527725.0,87833459.0,1526215.0
17,Kerala,18.0,26370455.0,21558246.0,47928701.0,318610.0
18,Ladakh,19.0,215780.0,176050.0,391830.0,5018.0
19,Lakshadweep,20.0,56175.0,53092.0,109267.0,1823.0
20,Madhya Pradesh,21.0,52743860.0,50520223.0,103264083.0,1970970.0
21,Maharashtra,22.0,81197428.0,55626731.0,136824159.0,1483877.0
22,Manipur,23.0,1333806.0,1005182.0,2338988.0,4381.0
23,Meghalaya,24.0,1243080.0,895169.0,2138249.0,5912.0
24,Mizoram,25.0,750199.0,591411.0,1341610.0,10392.0
25,Nagaland,26.0,760450.0,579961.0,1340411.0,1200.0
26,Odisha,27.0,29697758.0,21870982.0,51568740.0,412003.0
27,Puducherry,28.0,855834.0,576678.0,1432512.0,18928.0
28,Punjab,29.0,17412664.0,9791030.0,27203694.0,24683.0
29,Rajasthan,30.0,47488007.0,36061353.0,83549360.0,1618130.0
30,Sikkim,31.0,529700.0,484483.0,1014183.0,10557.0
31,Tamil Nadu,32.0,50672703.0,34827655.0,85500358.0,1463852.0
32,Telangana,33.0,28268742.0,19890649.0,48159391.0,608895.0
33,Tripura,34.0,2599926.0,2139818.0,4739744.0,70887.0
34,Uttar Pradesh,35.0,131171604.0,77702415.0,208874019.0,1716491.0
35,Uttarakhand,36.0,7908600.0,6551063.0,14459663.0,266268.0
36,West Bengal,37.0,65217243.0,42698608.0,107915851.0,1039409.0

In [ ]:
for i in states[0:7]:
    index = splitex.index(i)
    state_no = int(splitex[index-1])
    state_name = splitex[index]
    stname_no = [state_name,state_no]
    doses= splitex[index+1:index+5]
    total = stname_no +[int(i.replace(",","")) for i in doses]
    state_doses =state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)
print(state_doses.head())

In [ ]:
display(state_doses)

In [ ]:
index = splitex.index('A & N Islands')
state_no = int(splitex[index-1])
state_name = splitex[index]
stname_no = [state_name,state_no]
doese= splitex[index+1:index+5]


total_doses =[int(i.replace(",","")) for i in doses]
state_doses.append(pd.Series(total,["state","state_num","1st_Dose", "2nd_Dose","Total_Doses","1st_Dose(15-18)"]),ignore_index=True)
df2 = {'state':(splitex[index]) , 'state_num': int(splitex[index-1]), '1st_Dose': total_doses[0],'2nd_Dose': total_doses[1],'Total_Doses': total_doses[2], '1st_Dose(15-18)': total_doses[3]}
df = df.append(df2, ignore_index = True)

In [ ]:
total

In [ ]:
state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)

In [ ]:
state_doses.info()

In [1]:
import re

In [11]:
items = ['goal', 'new', 'user', 'sit', 'eat', 'dinner']

x = [w for w in items if not re.search(r'e',w, re.IGNORECASE)]

In [12]:
x

['goal', 'sit']

In [18]:
ip = 'This note should not be NoTeD'
re.sub(r'note|NoTe','X',ip)

'This X should not be XD'

In [19]:
para = '''good start
Start working on that
project you always wanted
stars are shining brightly
hi there
start and try to
finish the book
bye'''

In [20]:
pat = re.compile('Start|starts',re.I)

In [21]:
for line in para.split('\n'):
    if not pat.search(line):
        print(line)

project you always wanted
stars are shining brightly
hi there
finish the book
bye

In [22]:
items = ['goal', 'new', 'user', 'sit', 'eat', 'dinner']
[w for w in items if re.search('a',w) or re.search('w',w)]

['goal', 'new', 'eat']

In [23]:
items = ['goal', 'new', 'user', 'sit', 'eat', 'dinner']
[w for w in items if re.search('e',w) and re.search('n',w)]

['new', 'dinner']

In [ ]:
ip = 'start address: 0xA0, func1 address: 0xC0'