In [1]:
import PyPDF2 as pdf

In [2]:
df = open('CummulativeCovidVaccinationReport07January2022.pdf',"rb")

In [3]:
pdfReader = pdf.PdfFileReader(df)

In [4]:
pageObj = pdfReader.getPage(0)
extract= pageObj.extractText()

In [5]:
extract

"(As on 08 Jan'22 at 7 AM)\n15-18 Years\n1st Dose\n2nd Dose\nTotal Doses\n1st Dose\n85,83,23,079\n62,76,35,244\n1,48,59,58,323\n2,02,34,580\n(22,72,120 in last 24 \nHours )\n(35,31,325 in last 24 \nHours)\n(58,03,445 in last 24 \nHours)\n(32,55,915 in last 24 \nHours )\n0\n0\n0\n0\n15-18 Years\n1st Dose\n2nd Dose\nTotal Doses\n1st Dose\n1\nA & N Islands\n3,03,740\n2,95,713\n5,99,453\n9,968\n2\nAndhra Pradesh\n4,00,82,487\n3,07,28,752\n7,08,11,239\n17,99,919\n3\nArunachal Pradesh\n8,11,910\n6,55,590\n14,67,500\n12,199\n4\nAssam\n2,19,27,601\n1,62,50,752\n3,81,78,353\n5,45,176\n5\nBihar\n5,84,94,171\n4,33,15,480\n10,18,09,651\n13,33,297\n6\nChandigarh\n10,28,191\n7,97,205\n1825396\n12278\n7\nChhattisgarh\n1,79,77,433\n1,25,78,825\n3,05,56,258\n6,93,543\n8\nDadra & Nagar \nHaveli\n4,14,480\n2,94,941\n709421\n14213\n9\nDaman & Diu\n2,93,562\n2,43,997\n537559\n8884\n10\nDelhi\n1,56,03,453\n1,15,73,778\n2,71,77,231\n2,04,882\n11\nGoa\n13,19,508\n11,20,515\n2440023\n33305\n12\nGujarat\n4,75,82,358\n4,33,84,764\n9,09,67,122\n17,71,871\n13\nHaryana\n2,07,73,925\n1,52,03,393\n3,59,77,318\n5,28,002\n14\nHimachal Pradesh\n59,29,163\n55,11,230\n1,14,40,393\n2,40,811\n15\nJammu & Kashmir\n97,43,018\n92,82,520\n1,90,25,538\n1,85,636\n16\nJharkhand\n1,90,00,422\n1,16,98,643\n3,06,99,065\n2,62,095\n17\nKarnataka\n4,83,05,734\n3,95,27,725\n8,78,33,459\n15,26,215\n18\nKerala\n2,63,70,455\n2,15,58,246\n4,79,28,701\n3,18,610\n19\nLadakh\n2,15,780\n1,76,050\n391830\n5018\n20\nLakshadweep\n56,175\n53,092\n109267\n1823\n21\nMadhya Pradesh\n5,27,43,860\n5,05,20,223\n10,32,64,083\n19,70,970\n22\nMaharashtra\n8,11,97,428\n5,56,26,731\n13,68,24,159\n14,83,877\n23\nManipur\n13,33,806\n10,05,182\n2338988\n4381\n24\nMeghalaya\n12,43,080\n8,95,169\n2138249\n5912\n25\nMizoram\n7,50,199\n5,91,411\n1341610\n10392\n26\nNagaland\n7,60,450\n5,79,961\n13,40,411\n1,200\n27\nOdisha\n2,96,97,758\n2,18,70,982\n5,15,68,740\n4,12,003\n28\nPuducherry\n8,55,834\n5,76,678\n1432512\n18928\n29\nPunjab\n1,74,12,664\n97,91,030\n2,72,03,694\n24,683\n30\nRajasthan\n4,74,88,007\n3,60,61,353\n8,35,49,360\n16,18,130\n31\nSikkim\n5,29,700\n4,84,483\n1014183\n10557\n32\nTamil Nadu\n5,06,72,703\n3,48,27,655\n8,55,00,358\n14,63,852\n33\nTelangana\n2,82,68,742\n1,98,90,649\n4,81,59,391\n6,08,895\n34\nTripura\n25,99,926\n21,39,818\n47,39,744\n70,887\n35\nUttar Pradesh\n13,11,71,604\n7,77,02,415\n20,88,74,019\n17,16,491\n36\nUttarakhand\n79,08,600\n65,51,063\n1,44,59,663\n2,66,268\n37\nWest Bengal\n6,52,17,243\n4,26,98,608\n10,79,15,851\n10,39,409\n38\nMiscellaneous\n22,37,909\n15,70,622\n38,08,531\n0\nBeneficiaries Vaccinated\n18+ Population\nCumulative Coverage Report of COVID-19 Vaccination\nS. No.\nState/UT\nBeneficiaries Vaccinated\n18+ Population\n"

In [6]:
splitex= extract.split('\n')

In [7]:
splitex

["(As on 08 Jan'22 at 7 AM)",
 '15-18 Years',
 '1st Dose',
 '2nd Dose',
 'Total Doses',
 '1st Dose',
 '85,83,23,079',
 '62,76,35,244',
 '1,48,59,58,323',
 '2,02,34,580',
 '(22,72,120 in last 24 ',
 'Hours )',
 '(35,31,325 in last 24 ',
 'Hours)',
 '(58,03,445 in last 24 ',
 'Hours)',
 '(32,55,915 in last 24 ',
 'Hours )',
 '0',
 '0',
 '0',
 '0',
 '15-18 Years',
 '1st Dose',
 '2nd Dose',
 'Total Doses',
 '1st Dose',
 '1',
 'A & N Islands',
 '3,03,740',
 '2,95,713',
 '5,99,453',
 '9,968',
 '2',
 'Andhra Pradesh',
 '4,00,82,487',
 '3,07,28,752',
 '7,08,11,239',
 '17,99,919',
 '3',
 'Arunachal Pradesh',
 '8,11,910',
 '6,55,590',
 '14,67,500',
 '12,199',
 '4',
 'Assam',
 '2,19,27,601',
 '1,62,50,752',
 '3,81,78,353',
 '5,45,176',
 '5',
 'Bihar',
 '5,84,94,171',
 '4,33,15,480',
 '10,18,09,651',
 '13,33,297',
 '6',
 'Chandigarh',
 '10,28,191',
 '7,97,205',
 '1825396',
 '12278',
 '7',
 'Chhattisgarh',
 '1,79,77,433',
 '1,25,78,825',
 '3,05,56,258',
 '6,93,543',
 '8',
 'Dadra & Nagar ',
 'Haveli',
 '4,14,480',
 '2,94,941',
 '709421',
 '14213',
 '9',
 'Daman & Diu',
 '2,93,562',
 '2,43,997',
 '537559',
 '8884',
 '10',
 'Delhi',
 '1,56,03,453',
 '1,15,73,778',
 '2,71,77,231',
 '2,04,882',
 '11',
 'Goa',
 '13,19,508',
 '11,20,515',
 '2440023',
 '33305',
 '12',
 'Gujarat',
 '4,75,82,358',
 '4,33,84,764',
 '9,09,67,122',
 '17,71,871',
 '13',
 'Haryana',
 '2,07,73,925',
 '1,52,03,393',
 '3,59,77,318',
 '5,28,002',
 '14',
 'Himachal Pradesh',
 '59,29,163',
 '55,11,230',
 '1,14,40,393',
 '2,40,811',
 '15',
 'Jammu & Kashmir',
 '97,43,018',
 '92,82,520',
 '1,90,25,538',
 '1,85,636',
 '16',
 'Jharkhand',
 '1,90,00,422',
 '1,16,98,643',
 '3,06,99,065',
 '2,62,095',
 '17',
 'Karnataka',
 '4,83,05,734',
 '3,95,27,725',
 '8,78,33,459',
 '15,26,215',
 '18',
 'Kerala',
 '2,63,70,455',
 '2,15,58,246',
 '4,79,28,701',
 '3,18,610',
 '19',
 'Ladakh',
 '2,15,780',
 '1,76,050',
 '391830',
 '5018',
 '20',
 'Lakshadweep',
 '56,175',
 '53,092',
 '109267',
 '1823',
 '21',
 'Madhya Pradesh',
 '5,27,43,860',
 '5,05,20,223',
 '10,32,64,083',
 '19,70,970',
 '22',
 'Maharashtra',
 '8,11,97,428',
 '5,56,26,731',
 '13,68,24,159',
 '14,83,877',
 '23',
 'Manipur',
 '13,33,806',
 '10,05,182',
 '2338988',
 '4381',
 '24',
 'Meghalaya',
 '12,43,080',
 '8,95,169',
 '2138249',
 '5912',
 '25',
 'Mizoram',
 '7,50,199',
 '5,91,411',
 '1341610',
 '10392',
 '26',
 'Nagaland',
 '7,60,450',
 '5,79,961',
 '13,40,411',
 '1,200',
 '27',
 'Odisha',
 '2,96,97,758',
 '2,18,70,982',
 '5,15,68,740',
 '4,12,003',
 '28',
 'Puducherry',
 '8,55,834',
 '5,76,678',
 '1432512',
 '18928',
 '29',
 'Punjab',
 '1,74,12,664',
 '97,91,030',
 '2,72,03,694',
 '24,683',
 '30',
 'Rajasthan',
 '4,74,88,007',
 '3,60,61,353',
 '8,35,49,360',
 '16,18,130',
 '31',
 'Sikkim',
 '5,29,700',
 '4,84,483',
 '1014183',
 '10557',
 '32',
 'Tamil Nadu',
 '5,06,72,703',
 '3,48,27,655',
 '8,55,00,358',
 '14,63,852',
 '33',
 'Telangana',
 '2,82,68,742',
 '1,98,90,649',
 '4,81,59,391',
 '6,08,895',
 '34',
 'Tripura',
 '25,99,926',
 '21,39,818',
 '47,39,744',
 '70,887',
 '35',
 'Uttar Pradesh',
 '13,11,71,604',
 '7,77,02,415',
 '20,88,74,019',
 '17,16,491',
 '36',
 'Uttarakhand',
 '79,08,600',
 '65,51,063',
 '1,44,59,663',
 '2,66,268',
 '37',
 'West Bengal',
 '6,52,17,243',
 '4,26,98,608',
 '10,79,15,851',
 '10,39,409',
 '38',
 'Miscellaneous',
 '22,37,909',
 '15,70,622',
 '38,08,531',
 '0',
 'Beneficiaries Vaccinated',
 '18+ Population',
 'Cumulative Coverage Report of COVID-19 Vaccination',
 'S. No.',
 'State/UT',
 'Beneficiaries Vaccinated',
 '18+ Population',
 '']

In [21]:
u = splitex.index("Karnataka")

In [30]:
splitex.index("Dadra & Nagar ")

70

In [22]:
x=splitex[u+1:u+5]
state_no = int(splitex[u-1])
state_name = splitex[u]
num_name = [state_name,state_no]
lst = [int(i.replace(",","")) for i in x]
total = num_name +lst

In [31]:
x

['4,83,05,734', '3,95,27,725', '8,78,33,459', '15,26,215']

In [23]:
total

['Karnataka', 17, 48305734, 39527725, 87833459, 1526215]

In [24]:
h = []
h.append(total)

In [25]:
h

[['Karnataka', 17, 48305734, 39527725, 87833459, 1526215]]

In [26]:
import pandas as pd

In [28]:
state_doses = pd.DataFrame({"state":[],
               "state_num":[],
               "1st Dose":[],
               "2nd Dose":[],
               "Total Doses":[],
               "1st Dose(15-18)":[]
                })

In [35]:
df2 =state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)
df2

,state,state_num,1st Dose,2nd Dose,Total Doses,1st Dose(15-18)
0,West Bengal,37.0,65217243.0,42698608.0,107915851.0,1039409.0

In [32]:
for i in states:
    if i == 'Dadra & Nagar Haveli':
        index = splitex.index("Dadra & Nagar ")
        state_no = int(splitex[index-1])
        state_name = splitex[index]
        stname_no = [state_name,state_no]
        state_name = splitex[index]
        doses= splitex[index+2:index+6]
        total = stname_no +[int(i.replace(",","")) for i in doses]
        state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)
        
    else:
        index = splitex.index(i)
        state_no = int(splitex[index-1])
        state_name = splitex[index]
        stname_no = [state_name,state_no]
        doses= splitex[index+1:index+5]
        total = stname_no +[int(i.replace(",","")) for i in doses]
        state_doses.append(pd.Series(total,["state","state_num","1st Dose", "2nd Dose","Total Doses","1st Dose(15-18)"]),ignore_index=True)

In [14]:
splitx = list(splitex)

In [15]:
splitx

['(As',
 'on',
 '08',
 "Jan'22",
 'at',
 '7',
 'AM)',
 '15-18',
 'Years',
 '1st',
 'Dose',
 '2nd',
 'Dose',
 'Total',
 'Doses',
 '1st',
 'Dose',
 '85,83,23,079',
 '62,76,35,244',
 '1,48,59,58,323',
 '2,02,34,580',
 '(22,72,120',
 'in',
 'last',
 '24',
 'Hours',
 ')',
 '(35,31,325',
 'in',
 'last',
 '24',
 'Hours)',
 '(58,03,445',
 'in',
 'last',
 '24',
 'Hours)',
 '(32,55,915',
 'in',
 'last',
 '24',
 'Hours',
 ')',
 '0',
 '0',
 '0',
 '0',
 '15-18',
 'Years',
 '1st',
 'Dose',
 '2nd',
 'Dose',
 'Total',
 'Doses',
 '1st',
 'Dose',
 '1',
 'A',
 '&',
 'N',
 'Islands',
 '3,03,740',
 '2,95,713',
 '5,99,453',
 '9,968',
 '2',
 'Andhra',
 'Pradesh',
 '4,00,82,487',
 '3,07,28,752',
 '7,08,11,239',
 '17,99,919',
 '3',
 'Arunachal',
 'Pradesh',
 '8,11,910',
 '6,55,590',
 '14,67,500',
 '12,199',
 '4',
 'Assam',
 '2,19,27,601',
 '1,62,50,752',
 '3,81,78,353',
 '5,45,176',
 '5',
 'Bihar',
 '5,84,94,171',
 '4,33,15,480',
 '10,18,09,651',
 '13,33,297',
 '6',
 'Chandigarh',
 '10,28,191',
 '7,97,205',
 '1825396',
 '12278',
 '7',
 'Chhattisgarh',
 '1,79,77,433',
 '1,25,78,825',
 '3,05,56,258',
 '6,93,543',
 '8',
 'Dadra',
 '&',
 'Nagar',
 'Haveli',
 '4,14,480',
 '2,94,941',
 '709421',
 '14213',
 '9',
 'Daman',
 '&',
 'Diu',
 '2,93,562',
 '2,43,997',
 '537559',
 '8884',
 '10',
 'Delhi',
 '1,56,03,453',
 '1,15,73,778',
 '2,71,77,231',
 '2,04,882',
 '11',
 'Goa',
 '13,19,508',
 '11,20,515',
 '2440023',
 '33305',
 '12',
 'Gujarat',
 '4,75,82,358',
 '4,33,84,764',
 '9,09,67,122',
 '17,71,871',
 '13',
 'Haryana',
 '2,07,73,925',
 '1,52,03,393',
 '3,59,77,318',
 '5,28,002',
 '14',
 'Himachal',
 'Pradesh',
 '59,29,163',
 '55,11,230',
 '1,14,40,393',
 '2,40,811',
 '15',
 'Jammu',
 '&',
 'Kashmir',
 '97,43,018',
 '92,82,520',
 '1,90,25,538',
 '1,85,636',
 '16',
 'Jharkhand',
 '1,90,00,422',
 '1,16,98,643',
 '3,06,99,065',
 '2,62,095',
 '17',
 'Karnataka',
 '4,83,05,734',
 '3,95,27,725',
 '8,78,33,459',
 '15,26,215',
 '18',
 'Kerala',
 '2,63,70,455',
 '2,15,58,246',
 '4,79,28,701',
 '3,18,610',
 '19',
 'Ladakh',
 '2,15,780',
 '1,76,050',
 '391830',
 '5018',
 '20',
 'Lakshadweep',
 '56,175',
 '53,092',
 '109267',
 '1823',
 '21',
 'Madhya',
 'Pradesh',
 '5,27,43,860',
 '5,05,20,223',
 '10,32,64,083',
 '19,70,970',
 '22',
 'Maharashtra',
 '8,11,97,428',
 '5,56,26,731',
 '13,68,24,159',
 '14,83,877',
 '23',
 'Manipur',
 '13,33,806',
 '10,05,182',
 '2338988',
 '4381',
 '24',
 'Meghalaya',
 '12,43,080',
 '8,95,169',
 '2138249',
 '5912',
 '25',
 'Mizoram',
 '7,50,199',
 '5,91,411',
 '1341610',
 '10392',
 '26',
 'Nagaland',
 '7,60,450',
 '5,79,961',
 '13,40,411',
 '1,200',
 '27',
 'Odisha',
 '2,96,97,758',
 '2,18,70,982',
 '5,15,68,740',
 '4,12,003',
 '28',
 'Puducherry',
 '8,55,834',
 '5,76,678',
 '1432512',
 '18928',
 '29',
 'Punjab',
 '1,74,12,664',
 '97,91,030',
 '2,72,03,694',
 '24,683',
 '30',
 'Rajasthan',
 '4,74,88,007',
 '3,60,61,353',
 '8,35,49,360',
 '16,18,130',
 '31',
 'Sikkim',
 '5,29,700',
 '4,84,483',
 '1014183',
 '10557',
 '32',
 'Tamil',
 'Nadu',
 '5,06,72,703',
 '3,48,27,655',
 '8,55,00,358',
 '14,63,852',
 '33',
 'Telangana',
 '2,82,68,742',
 '1,98,90,649',
 '4,81,59,391',
 '6,08,895',
 '34',
 'Tripura',
 '25,99,926',
 '21,39,818',
 '47,39,744',
 '70,887',
 '35',
 'Uttar',
 'Pradesh',
 '13,11,71,604',
 '7,77,02,415',
 '20,88,74,019',
 '17,16,491',
 '36',
 'Uttarakhand',
 '79,08,600',
 '65,51,063',
 '1,44,59,663',
 '2,66,268',
 '37',
 'West',
 'Bengal',
 '6,52,17,243',
 '4,26,98,608',
 '10,79,15,851',
 '10,39,409',
 '38',
 'Miscellaneous',
 '22,37,909',
 '15,70,622',
 '38,08,531',
 '0',
 'Beneficiaries',
 'Vaccinated',
 '18+',
 'Population',
 'Cumulative',
 'Coverage',
 'Report',
 'of',
 'COVID-19',
 'Vaccination',
 'S.',
 'No.',
 'State/UT',
 'Beneficiaries',
 'Vaccinated',
 '18+',
 'Population']

In [9]:
extraction = [i for i in splitex]

In [10]:
extraction

['(As',
 'on',
 '08',
 "Jan'22",
 'at',
 '7',
 'AM)',
 '15-18',
 'Years',
 '1st',
 'Dose',
 '2nd',
 'Dose',
 'Total',
 'Doses',
 '1st',
 'Dose',
 '85,83,23,079',
 '62,76,35,244',
 '1,48,59,58,323',
 '2,02,34,580',
 '(22,72,120',
 'in',
 'last',
 '24',
 'Hours',
 ')',
 '(35,31,325',
 'in',
 'last',
 '24',
 'Hours)',
 '(58,03,445',
 'in',
 'last',
 '24',
 'Hours)',
 '(32,55,915',
 'in',
 'last',
 '24',
 'Hours',
 ')',
 '0',
 '0',
 '0',
 '0',
 '15-18',
 'Years',
 '1st',
 'Dose',
 '2nd',
 'Dose',
 'Total',
 'Doses',
 '1st',
 'Dose',
 '1',
 'A',
 '&',
 'N',
 'Islands',
 '3,03,740',
 '2,95,713',
 '5,99,453',
 '9,968',
 '2',
 'Andhra',
 'Pradesh',
 '4,00,82,487',
 '3,07,28,752',
 '7,08,11,239',
 '17,99,919',
 '3',
 'Arunachal',
 'Pradesh',
 '8,11,910',
 '6,55,590',
 '14,67,500',
 '12,199',
 '4',
 'Assam',
 '2,19,27,601',
 '1,62,50,752',
 '3,81,78,353',
 '5,45,176',
 '5',
 'Bihar',
 '5,84,94,171',
 '4,33,15,480',
 '10,18,09,651',
 '13,33,297',
 '6',
 'Chandigarh',
 '10,28,191',
 '7,97,205',
 '1825396',
 '12278',
 '7',
 'Chhattisgarh',
 '1,79,77,433',
 '1,25,78,825',
 '3,05,56,258',
 '6,93,543',
 '8',
 'Dadra',
 '&',
 'Nagar',
 'Haveli',
 '4,14,480',
 '2,94,941',
 '709421',
 '14213',
 '9',
 'Daman',
 '&',
 'Diu',
 '2,93,562',
 '2,43,997',
 '537559',
 '8884',
 '10',
 'Delhi',
 '1,56,03,453',
 '1,15,73,778',
 '2,71,77,231',
 '2,04,882',
 '11',
 'Goa',
 '13,19,508',
 '11,20,515',
 '2440023',
 '33305',
 '12',
 'Gujarat',
 '4,75,82,358',
 '4,33,84,764',
 '9,09,67,122',
 '17,71,871',
 '13',
 'Haryana',
 '2,07,73,925',
 '1,52,03,393',
 '3,59,77,318',
 '5,28,002',
 '14',
 'Himachal',
 'Pradesh',
 '59,29,163',
 '55,11,230',
 '1,14,40,393',
 '2,40,811',
 '15',
 'Jammu',
 '&',
 'Kashmir',
 '97,43,018',
 '92,82,520',
 '1,90,25,538',
 '1,85,636',
 '16',
 'Jharkhand',
 '1,90,00,422',
 '1,16,98,643',
 '3,06,99,065',
 '2,62,095',
 '17',
 'Karnataka',
 '4,83,05,734',
 '3,95,27,725',
 '8,78,33,459',
 '15,26,215',
 '18',
 'Kerala',
 '2,63,70,455',
 '2,15,58,246',
 '4,79,28,701',
 '3,18,610',
 '19',
 'Ladakh',
 '2,15,780',
 '1,76,050',
 '391830',
 '5018',
 '20',
 'Lakshadweep',
 '56,175',
 '53,092',
 '109267',
 '1823',
 '21',
 'Madhya',
 'Pradesh',
 '5,27,43,860',
 '5,05,20,223',
 '10,32,64,083',
 '19,70,970',
 '22',
 'Maharashtra',
 '8,11,97,428',
 '5,56,26,731',
 '13,68,24,159',
 '14,83,877',
 '23',
 'Manipur',
 '13,33,806',
 '10,05,182',
 '2338988',
 '4381',
 '24',
 'Meghalaya',
 '12,43,080',
 '8,95,169',
 '2138249',
 '5912',
 '25',
 'Mizoram',
 '7,50,199',
 '5,91,411',
 '1341610',
 '10392',
 '26',
 'Nagaland',
 '7,60,450',
 '5,79,961',
 '13,40,411',
 '1,200',
 '27',
 'Odisha',
 '2,96,97,758',
 '2,18,70,982',
 '5,15,68,740',
 '4,12,003',
 '28',
 'Puducherry',
 '8,55,834',
 '5,76,678',
 '1432512',
 '18928',
 '29',
 'Punjab',
 '1,74,12,664',
 '97,91,030',
 '2,72,03,694',
 '24,683',
 '30',
 'Rajasthan',
 '4,74,88,007',
 '3,60,61,353',
 '8,35,49,360',
 '16,18,130',
 '31',
 'Sikkim',
 '5,29,700',
 '4,84,483',
 '1014183',
 '10557',
 '32',
 'Tamil',
 'Nadu',
 '5,06,72,703',
 '3,48,27,655',
 '8,55,00,358',
 '14,63,852',
 '33',
 'Telangana',
 '2,82,68,742',
 '1,98,90,649',
 '4,81,59,391',
 '6,08,895',
 '34',
 'Tripura',
 '25,99,926',
 '21,39,818',
 '47,39,744',
 '70,887',
 '35',
 'Uttar',
 'Pradesh',
 '13,11,71,604',
 '7,77,02,415',
 '20,88,74,019',
 '17,16,491',
 '36',
 'Uttarakhand',
 '79,08,600',
 '65,51,063',
 '1,44,59,663',
 '2,66,268',
 '37',
 'West',
 'Bengal',
 '6,52,17,243',
 '4,26,98,608',
 '10,79,15,851',
 '10,39,409',
 '38',
 'Miscellaneous',
 '22,37,909',
 '15,70,622',
 '38,08,531',
 '0',
 'Beneficiaries',
 'Vaccinated',
 '18+',
 'Population',
 'Cumulative',
 'Coverage',
 'Report',
 'of',
 'COVID-19',
 'Vaccination',
 'S.',
 'No.',
 'State/UT',
 'Beneficiaries',
 'Vaccinated',
 '18+',
 'Population']

In [13]:
extraction.index('Bihar',)

87

In [ ]:
states = [A & N Islands
Andhra Pradesh
Arunachal Pradesh
Assam
Bihar
Chandigarh
Chhattisgarh
Dadra & Nagar Haveli
Daman & Diu
Delhi
Goa
Gujarat
Haryana
Himachal Pradesh
Jammu & Kashmir
Jharkhand
Karnataka
Kerala
Ladakh
Lakshadweep
Madhya Pradesh
Maharashtra
Manipur
Meghalaya
Mizoram
Nagaland
Odisha
Puducherry
Punjab
Rajasthan
Sikkim
Tamil Nadu
Telangana
Tripura
Uttar Pradesh
Uttarakhand
West Bengal
]

In [ ]:
import pandas as pd
data = pd.read_csv("states.csv")

In [ ]:
data.head()

In [ ]:
states= [i for i in data["State_name"]]

In [9]:
states = ['A & N Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli',
 'Daman & Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [ ]:
states

In [22]:
x =splitex.index("A & N Islands")
print(splitex[(x-1):(x+5)])

['1', 'A & N Islands', '3,03,740', '2,95,713', '5,99,453', '9,968']

In [ ]:
len(extract)

In [ ]:
splitex = extract.split()

In [ ]:
len(splitex)

In [ ]:
x =splitex.index("Maharashtra")

In [ ]:
print(x)

In [ ]:
print(splitex[(x-1):(x+5)])

we can make new data frame for all

In [ ]:
v=int(splitex[199].replace(",",""))
print(v)

In [ ]:
len(extract)
splitex = extract.split()
x =splitex.index("Andhra Pradesh")
print(splitex[(x-1):(x+5)])